### PR TITLE
[FIX] Various fixes and improvements

### LINKED ISSUE #132: Controller is not able to patch InfobloxIPPool status conditions
Updating status conditions of IPPools does not work and fails with the following error.

```
"Reconciler error" err="failed to patch InfobloxIPPool <namespace>/<name>: InfobloxIPPool.ipam.cluster.x-k8s.io \"<name>\" is invalid: [status.conditions[0].message: Required value, status.conditions[0].reason: Required value]"
```

Especially when a failure condition was added to the IPPool, this prohibits the reconciler to remove this condition again and the IPPool is marked as failed forever.

### PR DESCRIPTION
**Pull request by Arakos**
# Features

* update API types to support SSA patches for objects
* add basic infoblox error message parsing (falls back to raw error if not possible)
* assert that a hostname for a claim has the DNSZone suffix if a DNSZone is set on the referenced IPPool

# Fixes
* improve API type validation to actually do as intended (fixes https://github.com/telekom/cluster-api-ipam-provider-infoblox/issues/132) 
* fix the known issue with infoblox not returning some fields for hostrecords by using the correct request method
* fix setup (readme, make release) to correctly reflect latest clusterctl init requirements
* fix controllertools and setup-envtest versions and make them managed by go.mod
* fixed controller params to correctly pass cert-key and name params to the related options struct
* only check if an instances default network view exists if a view is configured (the field is optional, so don't validate existance for an emtpy value)

### CODE REVIEW

File: pkg/infoblox/addresses.go [hunk 1]
```diff
@@ -4,41 +4,60 @@ import (
...
+func (c *client) getOrEmptyHostRecord(networkView, dnsView, dnsZone, hostname string) (*ibclient.HostRecord, error) {
 
-// getOrNewHostRecord returns the host record with the given hostname in the given view, or creates a new host record if no host record with the given hostname exists.
-func (c *client) getOrNewHostRecord(networkView, dnsView, hostname, zone string) (*ibclient.HostRecord, error) {
-	// [Issue] For some reason Infoblox does not assign view to the host record. Empty netview and dnsview is a workaround to find host.
-	hostRecord, err := c.objMgr.GetHostRecord("", "", hostname, "", "")
+	// if DNS is enabled but the hostname does not have the zone as suffix automatically assume it
+	if !strings.HasSuffix(hostname, dnsZone) {
+		hostname = fmt.Sprintf("%s.%s", hostname, dnsZone)
+	}
```
Comment (Arakos) [inline pkg/infoblox/addresses.go]: This new behavior is also up for debate.

Is that a good idea, or should we instead validate that (if a dnsZone is configured) the hostname values must have the correct suffix?

If not, we should return an error, because if we don't, Infoblox will return one with a cryptic message.

(Same as https://github.com/telekom/cluster-api-ipam-provider-infoblox/pull/131#discussion_r2791931687)

File: api/v1alpha1/infobloxinstance_types.go [hunk 2]
```diff
@@ -17,52 +17,86 @@ limitations under the License.
...
+	//
+	// +kubebuilder:validation:Required
+	CredentialsSecretRef CredentialsReferece `json:"credentialsSecretRef,omitzero"`
 
 	// DefaultNetworkView is the default network view used when interacting with Infoblox.
 	// InfobloxIPPools will inherit this value when not explicitly specifying a network view.
-	// +optional
-	DefaultNetworkView string `json:"defaultNetworkView,omitempty"`
+	//
+	// Note: We can consider adding a allowedNamespacesSelector, similar to CAPV, for access control.
```
Comment (schrej) [inline api/v1alpha1/infobloxinstance_types.go]: This comment doesn't belong to the `DefaultNetworkView`, but rather the entire resource. Maybe we should move it to the end of the struct? Or just remove it?

File: api/v1alpha1/infobloxippool_types.go [hunk 3]
```diff
@@ -1,48 +1,78 @@
...
 )
 
 // InfobloxIPPoolSpec defines the desired state of InfobloxIPPool.
 type InfobloxIPPoolSpec struct {
+
 	// Instance is the Infoblox instance to use.
-	InstanceRef corev1.LocalObjectReference `json:"instance"`
+	//
+	// +kubebuilder:validation:Required
+	InstanceRef InstanceReference `json:"instance,omitzero"`
```
Comment (schrej) [inline api/v1alpha1/infobloxippool_types.go:13]: Technically a breaking change, but since it's yaml compatible we can do it I think.

**Comment by Cellebyte** [comment]
@schrej @Arakos do you think this could be merged? We wasted now 2 days on this topic.

File: internal/controllers/infobloxinstance.go [hunk 4]
```diff
@@ -130,27 +130,30 @@ func (r *InfobloxInstanceReconciler) reconcile(ctx context.Context, instance *v1
...
 	if instance.Spec.DefaultDNSView != "" {
 		if ok, err := ibcl.CheckDNSViewExists(instance.Spec.DefaultDNSView); err != nil || !ok {
-			logger.Error(err, "could not find default DNS view", "dnsView", instance.Spec.DefaultDNSView)
+			logger.Error(err, "could not find default DNS view", "defaultDnsView", instance.Spec.DefaultDNSView)
 			conditions.Set(instance, metav1.Condition{
 				Type:    clusterv1.ReadyCondition,
 				Status:  metav1.ConditionFalse,
 				Reason:  v1alpha1.DNSViewNotFoundReason,
-				Message: fmt.Sprintf("could not find default DNS view: %s", err),
+				Message: fmt.Sprintf("could not find default DNS view: %s", instance.Spec.DefaultDNSView),
```
Comment (schrej) [inline internal/controllers/infobloxinstance.go]: I'd do this instead then
```suggestion
				Message: fmt.Sprintf("could not find default DNS view %q", instance.Spec.DefaultDNSView),
```

File: Makefile [hunk 5]
```diff
@@ -93,7 +93,7 @@ docker-push: ## Push docker image with the manager.
 
 RELEASE_TAG ?= $(shell git describe --tags --abbrev=0 2>/dev/null)
 
-RELEASE_DIR ?= out
+RELEASE_DIR ?= out/ipam-infoblox/$(RELEASE_TAG)
```
Comment (schrej) [inline Makefile:101]: This might interfere with the 'prepare release' GitHub action.

**Review by schrej — COMMENTED** [review]
a few nits, lgtm otherwise

File: api/v1alpha1/infobloxinstance_types.go (hunk 2 above)
Comment (Arakos) [reply api/v1alpha1/infobloxinstance_types.go]: Ah ok, tbh. I just moved it and gave its contents no further thought.

I'd probably remove it here and open an issue in github to have a reminder to think about it in the future.

File: api/v1alpha1/infobloxippool_types.go (hunk 3 above)
Comment (Arakos) [reply api/v1alpha1/infobloxippool_types.go:13]: It is a breaking change from the Kubernetes API POV as well as from a code library POV if someone includes the API types in their own code, yes.

The he `.name` field inside the reference is now mandatory during apply (in the corev1 ref it was optional).

This technically does not change anything; it only moves possible error messages related to the empty reference value earlier (when you try to apply the resource, not after you applied it and its status stays in NotReady forever because there is no instance ref).

But the earlier you find such errors the better - so I'd change it.

Comment (schrej) [reply api/v1alpha1/infobloxippool_types.go:13]: Yeah, all fine. If someone provided GVK info, so be it. It was ignored before and will be ignored now.

File: internal/controllers/infobloxinstance.go (hunk 4 above)
Comment (Arakos) [reply internal/controllers/infobloxinstance.go]: I fixed it in the current version.

File: Makefile (hunk 5 above)
Comment (Arakos) [reply Makefile:101]: I (think) the build action should now be fixed as well.

File: pkg/infoblox/addresses.go (hunk 1 above)
Comment (Arakos) [reply pkg/infoblox/addresses.go]: We decided not to introduce this but throw an error if the hostname does not have the dnsZone as suffix if a dnsZone value other then "" is set.

File: api/v1alpha1/infobloxinstance_types.go (hunk 2 above)
Comment (Arakos) [reply api/v1alpha1/infobloxinstance_types.go]: I removed the note from the comment entirely.

**Review by schrej — APPROVED** [review]
